[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter=@theglobalconnect/db db:generate',
  'pnpm --filter=@theglobalconnect/web build'
]

[start]
cmd = 'cd apps/web && pnpm start'