[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@8 --activate',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'echo "Building..."',
  'cd apps/web && pnpm build'
]

[start]
cmd = './start.sh'